### ISSUE TITLE
Skills and skill Msgs

### ISSUE THREAD

**Issue by Reeson2003** [Reeson2003/MyGameNew#3]
Invent how to contain skills. Implement simple attack skill and simple heal skill with messages.

**Comment by Reeson2003** [comment]
Make coordinates. Counting distance, with barriers. Getting list of objects around the player.

**Comment by Nimtego** [comment]
Dude why in English? By the way do you know the meaning of the word still "dude"?

**Comment by Reeson2003** [comment]
Возможно сделать Map для абилити в Creature с ключом "name". Тогда в Creature добавить метод возвращающий абилити по имени.
